services: 
  app: 
    build: ./app/
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
      - ./db/.env.dev
    depends_on:
      - db
  db: 
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.dev
volumes: 
  postgres_data:
