services: 
  app: 
    build: ./app/
    volumes:
      - static_volume:/usr/src/app/blog/staticfiles
    command: gunicorn homelab_blog.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
  db: 
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.prod.db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/blog/staticfiles
    ports:
      - 1337:80
    depends_on:
      - app
volumes: 
  postgres_data:
  static_volume:

