services: 
  app: 
    build: ./app/
    volumes:
      - static_volume:/usr/src/app/blog/staticfiles
    command: gunicorn homelab_blog.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
  restart: always
  db: 
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.prod.db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/blog/staticfiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot: 
    image: certbot/certbot
    restart: unless-stopped
    volumes: 
      - ./certbot/conf:/etc/letsencrypt 
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes: 
  postgres_data:
  static_volume:

