name: CI/CD for django blog
on: 
  workflow_dispatch:
  push: 
    branches: 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: fifsky/ssh-action@master
        with: 
          command: | 
            rm -rf ~/homelab-blog
            git clone git@github.com:skogrv/homelab-blog.git ~/homelab-blog
            cd homelab-blog
            echo "${{ secrets.ENV_PROD }}" > app/.env.prod
            echo "${{ secrets.ENV_PROD_DB }}" > db/.env.prod.db
            docker compose down --rmi all
            docker compose up --build -d
          host: ${{ secrets.VPS_HOST }}
          user: 'root'
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}

    